[tool.flet]
name = "faz launcher"
product = "Faz Launcher"
description = "A cross-platform launcher for Five Nights at Freddy's"
icon = "assets/launcher-icon.png"
assets = [
    "assets"
]


[project]
name = "fazlauncher"
version = "1.3.0"
description = "A cross-platform launcher for Five Nights at Freddy's"

dependencies = [
    "certifi>=2026.7.22",
    "flet>=0.86.5",
    "requests",
]